alias c := create
alias q := query
alias s := serve
alias t := test

# Show available recipes (default)
help:
  @just --list

# Create H2 database for Music Club
create:
  ./amper run -m create -- --sql

# Run some sample queries on the database
query:
  ./amper run -m query -- --sql

# Start the web application server
[no-exit-message]
serve:
  ./amper run -m server

# Test the web application
test:
  ./amper test -m server
